import { Inter } from "next/font/google";
import Head from "next/head";
import React from "react";
import Menu from "./menu";

const inter = Inter({ subsets: ['latin'] });

export default function Layout({children}: {children: React.ReactNode}) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${inter.className} `}>
      <Menu />

        <div className="min-h-screen flex flex-col justify-center items-center mx-4"> {children}
        </div>
      </main>
    </>
  )
}