import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div>CHRONOTYPE</div>
        </div>

        <div className={styles.center}>
          <h1>What is your chronotype?</h1>
        </div>
        <div style={{ maxWidth: '700px', marginBottom: '5%' }}>
          <p style={{ textAlign: 'center', marginBottom: '10px' }}>
            We’re all familiar with the phrases “early bird” and “night owl.”
            Some of us are able to wake right up in the morning and start the
            day immediately, while some of us function much better at night.
            Everyone’s daily schedules work differently because our bodies all
            work differently.
          </p>

          <p style={{ textAlign: 'center', marginBottom: '10px' }}>
            Our bodies function according to our own unique biological clock—
            part of this includes our chronotypes. I talk about chronotypes a
            lot because they’re a very important part of getting a good night’s
            sleep.
          </p>
          <p style={{ textAlign: 'center', marginBottom: '10px' }}>
            In case you’re not familiar with chronotypes though, I hope this
            helpful guide can fill in some of the blanks you have on the
            subject. Sleeping according to your chronotype’s preferred schedule
            can make a huge difference in getting the quality sleep you need
            each night, even if you don’t follow what may be considered a
            “normal” sleep schedule.
          </p>
          <p style={{ textAlign: 'center' }}>
            But before we get much further, let’s take a look at what
            chronotypes are, and why they’re important to our daily function.
          </p>
        </div>
        <div className={styles.center}>
          <Link href="/about" className={styles.card}>
              <h2>
                About <span>-&gt;</span>
              </h2>
              <p>What is Chronotype?</p>
          </Link>
          <Link href="/chronotypes" className={styles.card}>
              <h2>
                Chronotypes <span>-&gt;</span>
              </h2>
              <p>Learn all chronotypes!</p>
          </Link>
          <Link href="/quiz" className={styles.card}>
            <h2>
              Chronotype Quiz<span>-&gt;</span>
            </h2>
            <p>Learn your chronotype!</p>
          </Link>

        
        </div>
      </main>
    </>
  );
}
